### ISSUE TITLE
analyser_osmosis_wikipedia.py: TypeError: 'instancemethod' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#221]
analyser_osmosis_wikipedia.py recently starts failing

backend is synchronized to HEAD

please let me know what further details you need.

```
2017-07-31 03:15:24   ./analysers/analyser_osmosis_wikipedia.py:84 xml generation
('res=', [[u'N4069455761', u'N4127461013', u'N4104051920', u'N4087646625', u'N3868709839', u'N3868709842', u'N3855865769', u'N3870411611', u'N3855865
767', u'N4057535957', u'N3848872920', u'N3755679504', u'N3848872926', u'N3848447858', u'N3856165823', u'N3927955173', u'N4057535966', u'N3864514737',
 u'N4443342199', u'N3927955172', u'N3755679498', u'N4443342196', u'N3864514725', u'N3927955171', u'N3868709835', u'N3956798487', u'N4057535961', u'N4
072963241', u'N4057535955', u'N3755679496', u'N3862581363', u'N3856165776', u'N3864514728', u'N4081114160', u'N3856165843', u'N3868710065', u'N385616
5842', u'N4087646627', u'N4057535958', u'N4057535959', u'N3856165833', u'N3868706683', u'N3755679499', u'N3864514734', u'N3864514729', u'N4069455764'
, u'N4412914792', u'N3868710067', u'N3934825740', u'N3856165821', u'N4412914770', u'N3856165831', u'N4087646264', u'N3855865771', u'N4443342198', u'N
3868706684', u'N3868709807', u'N3860563890', u'N4127461043', u'N3848447859', u'N4433825779', u'N4127461027', u'N3779245993', u'N4069455762', u'N38484
47849', u'N3855865775', u'N3855865770', u'N4443342197', u'N3864514726', u'N3848447862', u'N3760252031', u'N3856165824', u'N3856165822', u'N3730272775
', u'N3848447844', u'N4069455754', u'N4087646233', u'N3760252024', u'N3868709800', u'N3934825742', u'N3856165766', u'N3927955176', u'N3868710077', u'
N3868709840', u'N3868709834', u'N3773034693', u'N3848872922', u'N3864514736', u'N3755679497', u'N3856165826', u'N4089416491', u'N4433826811', u'N4433
826475', u'N3868709830', u'N3855865766', u'N4057535954', u'N3773034695', u'N3848872925', u'N3856165846', u'N4127461003', u'N3856165765', u'N412746102
9', u'N4087646604', u'N3848447861', u'N3848872921', u'N3773034696', u'N3868709831', u'N3855865773', u'N4057535956', u'N4057535963', u'N4072963245', u
'N3868709837', u'N4087646626', u'N3855865765', u'N4433826810', u'N3760252030', u'N3848447845', u'N3870411610', u'N4057535965', u'N3935445850', u'N408
7646628', u'N3755679503', u'N3856165773', u'N3855865772', u'N3934825747', u'N3848447852', u'N4069455760', u'N4087646623', u'N3848447840', u'N38484478
55', u'N3927955175', u'N3848447857', u'N3848872918', u'N3760252023', u'N4057535964', u'N3935445853', u'N3848447856', u'N4129367898', u'N4127461005', 
u'N4087646237', u'N4412914787', u'N4057535960', u'N3848447838', u'N4087646603', u'N4087646624', u'N3856165808', u'N4087646234', u'N4433826440'], u'PO
INT(99.0055947 18.7650409)', u'en:Dipterocarpus_alatus'])
('ret=', None)                                                                                                                                       
2017-07-31 03:15:24   error on analyse...                                                                                                            
2017-07-31 03:15:24     Traceback (most recent call last):                                                                                           
2017-07-31 03:15:24       File "./osmose_run.py", line 643, in run                                                                                   
2017-07-31 03:15:24         analyser_obj.analyser()                                                                                                  
2017-07-31 03:15:24       File "./analysers/Analyser_Osmosis.py", line 173, in analyser                                                              
2017-07-31 03:15:24         self.analyser_osmosis_full()                                                                                             
2017-07-31 03:15:24       File "./analysers/analyser_osmosis_wikipedia.py", line 84, in analyser_osmosis_full                                        
2017-07-31 03:15:24         self.run(sql10.format("", ""), lambda res: {"class":1, "data":[self.array_full[0:10], self.positionAsText], "text": {"en"
: res[2]}})
2017-07-31 03:15:24       File "./analysers/Analyser_Osmosis.py", line 392, in run                                                                   
2017-07-31 03:15:24         self.run0(sql, callback_package)                                                                                         
2017-07-31 03:15:24       File "./analysers/Analyser_Osmosis.py", line 362, in run0                                                                  
2017-07-31 03:15:24         ret = callback(res)
2017-07-31 03:15:24       File "./analysers/Analyser_Osmosis.py", line 370, in callback_package
2017-07-31 03:15:24         ret = callback(res)
2017-07-31 03:15:24       File "./analysers/analyser_osmosis_wikipedia.py", line 84, in <lambda>
2017-07-31 03:15:24         self.run(sql10.format("", ""), lambda res: {"class":1, "data":[self.array_full[0:10], self.positionAsText], "text": {"en"
: res[2]}})
2017-07-31 03:15:24     TypeError: 'instancemethod' object has no attribute '__getitem__'
2017-07-31 03:15:24     

```

**Comment by frodrigo** [comment]
Bug introduced by https://github.com/osm-fr/osmose-backend/commit/1111ffd08ac0a4e36b780a6deeb25c068010e13b

**Comment by jocelynj** [comment]
Thanks. I've just pushed this fix.
